version: '3.1'

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    networks:
      - net
    restart: unless-stopped
    volumes:
      - .db:/data
  
  backend:
    container_name: weather_app_backend
    image: weather_app/backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports:
      - 8000:8000
    networks:
      - net
    restart: unless-stopped
    depends_on:
      - redis
  
  frontend:
    container_name: weather_app_frontend
    image: weather_app/frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - net
    restart: unless-stopped
    depends_on:
      - redis
      - backend

networks:
  net:
    driver: bridge

